server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=jdbc:postgresql://db.odvhobbmablnweeejrvg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Joao2006!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase JWT Secret (OBRIGATÓRIO)
supabase.jwt.secret=qWBidGZbpExY7SkCAs6udJAgDh4nZW3ymG625F1O+BpRWuU+m4WrLmxPGzCVySv4+DeYSz2aPE4Lp+7wIz1tHA==

# Server Configuration
server.port=8080

# (Opcional) Libera CORS para seu frontend local
spring.web.cors.allowed-origins=http://localhost:5500,http://127.0.0.1:5500